spring:
  application:
    name: server
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  google:
    cloud:
      credentials:
        location: src/main/resources/GCloudCredentials.json
logging:
  level:
    ROOT: INFO