spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://34.41.26.182:3306/easeflightdb
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  MySQL:
    console.enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  google:
    cloud:
      credentials:
        location: src/main/resources/GCloudCredentials.json
logging:
  level:
    ROOT: INFO
